A2EDC_MISSION_BUILD_ID = "20260526-133155";
A2EDC_MISSION_BUILD_UTC = "2026-05-26T13:31:55Z";
A2EDC_MISSION_BUILD_SOURCE = "MPMissions/dayz_1.origins.tavi";
A2EDC_MISSION_BUILD_PREFIX = "";
A2EDC_MISSION_BUILD_NOTE = "onback-v2-temp-self-action";
A2EDC_MISSION_BUILD_EXPORT = "Export/dayz_1.origins.tavi_20260526-133155_onback-v2-temp-self-action.pbo";
A2EDC_MISSION_BUILD_GIT_SHORT = "ee7eeb2";
A2EDC_MISSION_BUILD_GIT_DIRTY = "true";

diag_log format [
  "[A2EDC:MISSION_BUILD] dayz_1.origins.tavi.pbo build_id=%1 build_utc=%2 prefix=%3 note=%4 export=%5 git=%6 dirty=%7",
  A2EDC_MISSION_BUILD_ID,
  A2EDC_MISSION_BUILD_UTC,
  A2EDC_MISSION_BUILD_PREFIX,
  A2EDC_MISSION_BUILD_NOTE,
  A2EDC_MISSION_BUILD_EXPORT,
  A2EDC_MISSION_BUILD_GIT_SHORT,
  A2EDC_MISSION_BUILD_GIT_DIRTY
];
