/*
    A2EDC_itemWeights.sqf
    Reconstructed tooltip-only item weights for DayZ Origins/A2EDC.
    Generated from a2edc_item_weight_proposal_v1.tsv.
    These are NOT official Origins 1.7.9 values.
    Scope: client-side Gear tooltip display only.
    Must not be used for gameplay capacity, persistence, DB/Hive, sync, anti-dupe, loot, or server logic.
*/

if (isNil "A2EDC_itemWeightsReconstructed") then {
	A2EDC_itemWeightsReconstructed = [
		// category: food-drink
		["FoodCanBakedBeans",0.45,"A2EDC reconstructed proposal: food-drink; confidence=medium"],
		["FoodCanFrankBeans",0.45,"A2EDC reconstructed proposal: food-drink; confidence=medium"],
		["FoodCanPasta",0.45,"A2EDC reconstructed proposal: food-drink; confidence=medium"],
		["FoodCanSardines",0.35,"A2EDC reconstructed proposal: food-drink; confidence=medium"],
		["FoodSteakCooked",0.35,"A2EDC reconstructed proposal: food-drink; confidence=medium"],
		["FoodSteakRaw",0.40,"A2EDC reconstructed proposal: food-drink; confidence=medium"],
		["ItemSodaCoke",0.35,"A2EDC reconstructed proposal: food-drink; confidence=high"],
		["ItemSodaEmpty",0.05,"A2EDC reconstructed proposal: food-drink; confidence=medium"],
		["ItemSodaMdew",0.35,"A2EDC reconstructed proposal: food-drink; confidence=medium"],
		["ItemSodaPepsi",0.35,"A2EDC reconstructed proposal: food-drink; confidence=medium"],
		["ItemWaterbottle",1.00,"A2EDC reconstructed proposal: food-drink; confidence=medium"],
		["ItemWaterbottleUnfilled",0.15,"A2EDC reconstructed proposal: food-drink; confidence=medium"],
		// category: medical
		["ItemAntibiotic",0.10,"A2EDC reconstructed proposal: medical; confidence=medium"],
		["ItemBandage",0.50,"A2EDC reconstructed proposal: medical; confidence=high"],
		["ItemBloodbag",0.50,"A2EDC reconstructed proposal: medical; confidence=medium"],
		["ItemEpinephrine",0.15,"A2EDC reconstructed proposal: medical; confidence=medium"],
		["ItemHeatPack",0.10,"A2EDC reconstructed proposal: medical; confidence=medium"],
		["ItemMorphine",0.15,"A2EDC reconstructed proposal: medical; confidence=medium"],
		["ItemPainkiller",0.10,"A2EDC reconstructed proposal: medical; confidence=medium"],
		// category: consumable-chem-light
		["HandChemBlue",0.10,"A2EDC reconstructed proposal: consumable-chem-light; confidence=medium"],
		["HandChemGreen",0.10,"A2EDC reconstructed proposal: consumable-chem-light; confidence=medium"],
		["HandChemRed",0.10,"A2EDC reconstructed proposal: consumable-chem-light; confidence=medium"],
		// category: consumable-flare
		["HandRoadFlare",0.20,"A2EDC reconstructed proposal: consumable-flare; confidence=medium"],
		["RoadFlare",0.20,"A2EDC reconstructed proposal: consumable-flare; confidence=low"],
		// category: spray-can
		["ItemBlackSpr",0.35,"A2EDC reconstructed proposal: spray-can; confidence=medium"],
		["ItemBlueSpr",0.35,"A2EDC reconstructed proposal: spray-can; confidence=medium"],
		["ItemGreenSpr",0.35,"A2EDC reconstructed proposal: spray-can; confidence=medium"],
		["ItemPinkSpr",0.35,"A2EDC reconstructed proposal: spray-can; confidence=medium"],
		["ItemRedSpr",0.35,"A2EDC reconstructed proposal: spray-can; confidence=medium"],
		["ItemWhiteSpr",0.35,"A2EDC reconstructed proposal: spray-can; confidence=medium"],
		["ItemYellowSpr",0.35,"A2EDC reconstructed proposal: spray-can; confidence=medium"],
		// category: key
		["ItemKey",0.05,"A2EDC reconstructed proposal: key; confidence=medium"],
		["ItemKeyBlack",0.05,"A2EDC reconstructed proposal: key; confidence=medium"],
		["ItemKeyBlue",0.05,"A2EDC reconstructed proposal: key; confidence=medium"],
		["ItemKeyGreen",0.05,"A2EDC reconstructed proposal: key; confidence=medium"],
		["ItemKeyRed",0.05,"A2EDC reconstructed proposal: key; confidence=medium"],
		["ItemKeyYellow",0.05,"A2EDC reconstructed proposal: key; confidence=medium"],
		// category: blueprint-paper
		["ItemBpt_b1",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		["ItemBpt_b1e",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		["ItemBpt_b2",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		["ItemBpt_b2e",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		["ItemBpt_b3",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		["ItemBpt_b3e",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		["ItemBpt_g_b",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		["ItemBpt_g_s",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		["ItemBpt_h1",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		["ItemBpt_h1e",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		["ItemBpt_h2",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		["ItemBpt_h2e",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		["ItemBpt_h3",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		["ItemBpt_h3e",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		["ItemBpt_kr1",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		["ItemBpt_wt",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		["ItemBpt_wt1",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		["ItemBpt_wt2",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		["ItemBpt_wt3",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		["ItemBpt_wt4",0.05,"A2EDC reconstructed proposal: blueprint-paper; confidence=low"],
		// category: toolbelt-tool
		["Hatchet",1.50,"A2EDC reconstructed proposal: toolbelt-tool; confidence=low"],
		["ItemCompass",0.10,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["ItemCrowbar",2.50,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["ItemEtool",1.50,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["ItemFlashlight",0.30,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["ItemFlashlightRed",0.35,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["ItemGPS",0.25,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["ItemHammer",0.80,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["ItemHatchet",1.50,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["ItemKnife",0.25,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["ItemMap",0.05,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["ItemMatchbox",0.05,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["ItemPickaxe",3.00,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["ItemPliers",0.35,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["ItemRadio",0.30,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["ItemRope",1.00,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["ItemSaw",1.00,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["ItemToolBox",2.00,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["ItemToolbox",2.00,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["ItemTow",2.00,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["ItemWatch",0.05,"A2EDC reconstructed proposal: toolbelt-tool; confidence=medium"],
		["MeleeCrowbar",2.50,"A2EDC reconstructed proposal: toolbelt-tool; confidence=low"],
		["MeleeHatchet",1.50,"A2EDC reconstructed proposal: toolbelt-tool; confidence=low"],
		// category: crafting-building
		["CementMixer",15.00,"A2EDC reconstructed proposal: crafting-building; confidence=low"],
		["ItemBattery",5.00,"A2EDC reconstructed proposal: crafting-building; confidence=medium"],
		["ItemCementBag",12.00,"A2EDC reconstructed proposal: crafting-building; confidence=medium"],
		["ItemCinderblocks",10.00,"A2EDC reconstructed proposal: crafting-building; confidence=medium"],
		["ItemHose",1.20,"A2EDC reconstructed proposal: crafting-building; confidence=medium"],
		["ItemRestTent",6.00,"A2EDC reconstructed proposal: crafting-building; confidence=medium"],
		["ItemRocks",4.00,"A2EDC reconstructed proposal: crafting-building; confidence=medium"],
		["ItemScrews",0.20,"A2EDC reconstructed proposal: crafting-building; confidence=medium"],
		["ItemTent",5.00,"A2EDC reconstructed proposal: crafting-building; confidence=medium"],
		["batent",5.00,"A2EDC reconstructed proposal: crafting-building; confidence=low"],
		["bresttent",5.00,"A2EDC reconstructed proposal: crafting-building; confidence=low"],
		["reresttent",5.00,"A2EDC reconstructed proposal: crafting-building; confidence=low"],
		["rth_small_tent",5.00,"A2EDC reconstructed proposal: crafting-building; confidence=low"],
		["unbatent",5.00,"A2EDC reconstructed proposal: crafting-building; confidence=low"],
		// category: vehicle-part
		["ItemJerrycan",15.00,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["ItemJerrycanB",15.00,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["ItemJerrycanBEmpty",1.50,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["ItemJerrycanEmpty",1.50,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["ItemSandbag",8.00,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["ItemTankTrap",6.00,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["ItemWire",4.00,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["PartAluminium",2.00,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["PartBlockV",8.00,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["PartChipB",2.00,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["PartEngine",15.00,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["PartFueltank",8.00,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["PartGeneric",2.00,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["PartGlass",2.00,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["PartPipe",4.00,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["PartRock",8.00,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["PartScrap",3.00,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["PartVRotor",12.00,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["PartWheel",8.00,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["PartWoodPile",3.00,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		["Partscrap",3.00,"A2EDC reconstructed proposal: vehicle-part; confidence=medium"],
		// category: backpack-bag
		["DZ_ALICE_Pack_EP1",1.50,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["DZ_Assault_Pack_EP1",0.90,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["DZ_Backpack_EP1",2.00,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["DZ_CivilBackpack_EP1",1.20,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["DZ_CompactPack_EP1",0.80,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["DZ_Czech_Vest_Pouch",0.50,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["DZ_GunBag_EP1",2.50,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["DZ_LargeGunBag_EP1",3.00,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["DZ_Patrol_Pack_EP1",0.70,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["DZ_TK_Assault_Pack_EP1",0.90,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["DZ_TerminalPack_EP1",1.00,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["O_MegaPack_1",2.00,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["O_TravelerPack_1",1.30,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["ori_30l_Backpack",2.20,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["ori_bigrusruck",2.50,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["ori_vil_pack",1.20,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["origins_bear",1.00,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["origins_elephant1",1.00,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["origins_elephant2",1.00,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["origins_school_1",0.80,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["origins_school_2",0.80,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		["origins_school_3",0.80,"A2EDC reconstructed proposal: backpack-bag; confidence=medium"],
		// category: clothing-skin
		["DZ_British_ACU",0.80,"A2EDC reconstructed proposal: clothing-skin; confidence=low"],
		["Skin_Camo1_DZ",0.80,"A2EDC reconstructed proposal: clothing-skin; confidence=low"],
		["Skin_Sniper1_DZ",0.80,"A2EDC reconstructed proposal: clothing-skin; confidence=low"],
		["Skin_Soldier1_DZ",0.80,"A2EDC reconstructed proposal: clothing-skin; confidence=low"],
		["Skin_Survivor2_DZ",0.80,"A2EDC reconstructed proposal: clothing-skin; confidence=low"],
		["Skin_SurvivorW2_DZ",0.80,"A2EDC reconstructed proposal: clothing-skin; confidence=low"],
		// category: weapon
		["AKS_74",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AKS_74_Kobra",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AKS_74_PSO",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AKS_74_U",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AKS_74_UN_Kobra",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AKS_74_UN_kobra",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AKS_74_kobra",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AKS_74_pso",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AKS_GOLD",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AK_107_GL_Kobra",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AK_107_GL_PSO",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AK_107_GL_kobra",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AK_107_GL_pso",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AK_107_Kobra",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AK_107_PSO",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AK_107_kobra",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AK_107_pso",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AK_47_M",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AK_47_S",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AK_74",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AK_74_GL",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AK_74_GL_Kobra",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AK_74_GL_kobra",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["AS50",12.00,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["BAF_AS50_TWS",12.00,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["BAF_AS50_scoped",12.00,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["Crossbow",3.00,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["Colt1911",1.10,"A2EDC reconstructed proposal: weapon; confidence=medium; added from CfgLoot itemType weapon reference for M1911 validation"],
		["DMR",5.00,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["G36A_camo",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["G36C",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["G36C_camo",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["G36K",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["G36K_camo",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["G36_C_SD_camo",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["G36_C_SD_eotech",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["G36a",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["Huntingrifle",3.50,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["LeeEnfield",4.00,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M14_EP1",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M16A2",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M16A2GL",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M16A4_ACG",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M16A4_ACG_GL",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M16A4_GL",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M24",5.00,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M240",10.00,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M240_DZ",10.00,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M249",7.50,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M249_DZ",7.50,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M249_EP1",7.50,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M249_EP1_DZ",7.50,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M249_m145_EP1",7.70,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M24_des_EP1",5.00,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M40A3",5.00,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M4A1",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M4A1_AIM_SD",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M4A1_AIM_SD_camo",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M4A1_Aim",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M4A1_Aim_camo",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M4A1_HWS_GL",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M4A1_HWS_GL_SD_Camo",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M4A1_HWS_GL_camo",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M4A1_RCO_GL",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M4A3_CCO_EP1",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M4A3_RCO_GL_EP1",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M4SPR",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["M9SD",1.00,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["MG36",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["MG36_camo",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["MP5A5",2.60,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["MP5SD",2.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["Makarov",0.73,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["MakarovSD",0.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["PK_DZ",9.00,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["RPK_74",5.00,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["SCAR_H_CQC_CCO",4.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["SCAR_H_CQC_CCO_SD",4.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["SCAR_H_LNG_Sniper",4.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["SCAR_H_LNG_Sniper_SD",4.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["SCAR_H_STD_EGLM_Spect",4.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["SCAR_L_CQC_CCO_SD",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["SCAR_L_CQC_EGLM_Holo",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["SCAR_L_CQC_Holo",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["SCAR_L_STD_EGLM_RCO",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["SCAR_L_STD_HOLO",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["SCAR_L_STD_Mk4CQT",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["SM4",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["SVD",4.30,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["SVD_CAMO",4.30,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["SVD_NSPU_EP1",4.60,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["SVD_des_EP1",4.30,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["Sa58P_EP1",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["Sa58V_CCO_EP1",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["Sa58V_EP1",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["Sa58V_RCO_EP1",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["Winchester1866",3.30,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["glock17_EP1",0.90,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["huntingrifle",3.50,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["m107",12.00,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["m16a4",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["m16a4_acg",3.80,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["m240_scoped_EP1",10.00,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["revolver_EP1",1.10,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		["revolver_gold_EP1",1.10,"A2EDC reconstructed proposal: weapon; confidence=medium"],
		// category: misc-review
		["ItemCeMix",10.00,"A2EDC reconstructed proposal: misc-review; confidence=low"],
		["ItemCrane",12.00,"A2EDC reconstructed proposal: misc-review; confidence=low"],
		["ItemMTubes",4.00,"A2EDC reconstructed proposal: misc-review; confidence=medium"],
		["ItemMachete",1.00,"A2EDC reconstructed proposal: misc-review; confidence=low"],
		["ItemPin",0.05,"A2EDC reconstructed proposal: misc-review; confidence=low"],
		["Ori_PPS43",3.00,"A2EDC reconstructed proposal: misc-review; confidence=medium"],
		["Ori_Sa48SMG",3.30,"A2EDC reconstructed proposal: misc-review; confidence=medium"],
		["Ori_Tt33",0.85,"A2EDC reconstructed proposal: misc-review; confidence=medium"],
		["Ori_cz75",1.00,"A2EDC reconstructed proposal: misc-review; confidence=medium"],
		["Ori_cz83",0.80,"A2EDC reconstructed proposal: misc-review; confidence=medium"],
		["Ori_mossberg",3.20,"A2EDC reconstructed proposal: misc-review; confidence=medium"],
		["ori_vil_uzi_rozkl",2.70,"A2EDC reconstructed proposal: misc-review; confidence=medium"],
		["ori_vil_uzi_sd",2.90,"A2EDC reconstructed proposal: misc-review; confidence=medium"],
		["ori_vil_uzimini",2.20,"A2EDC reconstructed proposal: misc-review; confidence=medium"],
		["ori_vil_uzimini_SD",2.40,"A2EDC reconstructed proposal: misc-review; confidence=medium"]
	];
};

A2EDC_fnc_getItemWeightKg = {
	private["_className","_weight","_entry"];
	_className = _this select 0;
	_weight = -1;

	if (isNil "A2EDC_itemWeightsReconstructed") exitWith {_weight};

	{
		_entry = _x;
		if (((_entry select 0) == _className)) exitWith {
			_weight = _entry select 1;
		};
	} forEach A2EDC_itemWeightsReconstructed;
	_weight
};

A2EDC_fnc_formatItemWeightKg = {
	private["_weight","_scaled","_whole","_fraction","_fractionText"];
	_weight = _this select 0;
	_scaled = round (_weight * 100);
	_whole = floor (_scaled / 100);
	_fraction = _scaled - (_whole * 100);
	_fractionText = format["%1",_fraction];
	if (_fraction < 10) then {
		_fractionText = format["0%1",_fraction];
	};
	format["%1.%2",_whole,_fractionText]
};
